UPDATE room SET state='可用房';
DELETE FROM book;
DELETE FROM book_room;
DELETE FROM book_money;
DELETE FROM book_room_category;
DELETE FROM book_history;
DELETE FROM check_in;
DELETE FROM check_in_group;
DELETE FROM check_in_guest;
DELETE FROM check_in_history;
DELETE FROM check_in_history_log;
DELETE FROM check_out;
DELETE FROM check_out_group;
DELETE FROM check_out_room;
DELETE FROM company_debt;
DELETE FROM company_debt_history;
DELETE FROM company_pay;
UPDATE company SET consume = 0 AND debt=0;
DELETE FROM cook_room;
DELETE FROM guest_map_check_in;
DELETE FROM debt;
DELETE FROM debt_history;
DELETE FROM debt_pay;
DELETE FROM free_detail;
DELETE FROM lost_room;
DELETE FROM user_log;
DELETE FROM vip_detail;
DELETE FROM protocol where temp=1;
DELETE FROM room_state_report;
DELETE FROM serial;
INSERT INTO serial (id, pay_serial, book_serial, self_account, group_account, check_out_serial,desk_book_serial,ck_serial,storage_in_serial,storage_out_serial,sauna_out_serial,company_pay_serial,sauna_group_serial,check_out_serial_fp) VALUES (1,'001','001','001','001','001','001','001','001','001','001','001','001','0001');
DELETE FROM desk_detail;
DELETE FROM desk_detail_history;
DELETE FROM desk_pay;
DELETE FROM desk_in;
DELETE FROM desk_in_history;
DELETE FROM desk_book;
DELETE FROM desk_book_history;
#2018-09-25
delete from accesslog;
delete from check_in_snapshot;
delete from check_out_pay_back;
delete from clean_room;
delete from desk_detail_cancel_all;
delete from desk_in_cancel_all;
delete from exception_record;
delete from guest_snapshot;
delete from night_date;
delete from pay_point_of_sale;
delete from report_store;
delete from room_shop_detail;
delete from room_snapshot;
delete from vip_detail_history;
delete from vip_history;
delete from vip_id_number;