server:
    port: 8080
    session:
      timeout: 0
logging:
    level:
        com.sygdsoft: DEBUG
    path: C:\report
night:
    action: 0 0 0 * * *
    protect: 0 59 23 * * *
register:
    number: 7111ef5477
    numberCK: 8eee10ab881
    numberSN: 9fff01ba991
hotel:
    hotelId: hotel
    ip: localhost
custom:
    datasource:
        names: yujianyifenghua,base_hotel,hotel
        yujianyifenghua:
            url: jdbc:mysql://localhost:3306/yujianyifenghua?characterEncoding=utf8&useSSL=true
            username: yujianyifenghua
            password: q123
            driver-class-name: com.mysql.jdbc.Driver
        base_hotel:
            url: jdbc:mysql://localhost:3306/base_hotel?characterEncoding=utf8&useSSL=true
            username: base_hotel
            password: q123
            driver-class-name: com.mysql.jdbc.Driver
        hotel:
            url: jdbc:mysql://localhost:3306/hotel?characterEncoding=utf8&useSSL=true
            username: hotel
            password: q123
            driver-class-name: com.mysql.jdbc.Driver
spring:
    datasource:
        name: hotel
        url: jdbc:mysql://${hotel.ip}:3306/hotel?characterEncoding=utf8&useSSL=true
        username: hotel
        password: q123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            suffix: .html
#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: tk.mybatis.springboot.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
# ctrl+shift+f9=热部署